# Generated by Django 5.0.13 on 2026-05-09 18:45

from django.db import migrations

REVOKE_AUDIT_FROM_READONLY = """
DO $$
BEGIN
    REVOKE SELECT ON mcp_sql_mcpquerylog FROM mcp_readonly_role;
EXCEPTION
    WHEN undefined_object THEN
        NULL;
END
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_sql", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            REVOKE_AUDIT_FROM_READONLY, reverse_sql=migrations.RunSQL.noop
        ),
    ]
