# Generated by Django 5.2.14 on 2026-05-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0006_remove_mcpquerylog_result_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAuthRejectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_pk', models.CharField(blank=True, default='', max_length=64)),
                ('application_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive_or_non_staff', 'User is not an active staff member'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User no longer holds mcp_sql.use_mcp_session'), ('no_session', 'User has no live Django session')], max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP auth rejection log',
                'verbose_name_plural': 'MCP auth rejection logs',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'started_at'], name='mcp_sql_mcp_user_id_f3108c_idx'), models.Index(fields=['reason', 'started_at'], name='mcp_sql_mcp_reason_9db624_idx')],
            },
        ),
    ]
