# Generated by Django 5.2.14 on 2026-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0008_revoke_mcpauthrejectionlog_grants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpauthrejectionlog',
            name='reason',
            field=models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive_or_non_staff', 'User is not an active staff member'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User no longer holds mcp_sql.use_mcp_session'), ('no_session', 'User has no live Django session'), ('session_logout', 'MCP tokens revoked on user logout')], max_length=64),
        ),
    ]
