# Generated by Django 5.2.14 on 2026-05-21 21:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_sql", "0009_alter_mcpauthrejectionlog_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpquerylog",
            name="tool",
            field=models.CharField(default="run_query", max_length=32),
        ),
    ]
