# Generated by Django 5.2.14 on 2026-05-27 09:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_sql", "0010_mcpquerylog_tool"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcpquerylog",
            options={
                "ordering": ("-started_at",),
                "verbose_name": "MCP query log",
                "verbose_name_plural": "MCP query logs",
            },
        ),
        migrations.AddField(
            model_name="mcpquerylog",
            name="profile",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="mcpauthrejectionlog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("bad_application", "Token not issued by an mcp-sql Application"),
                    ("bad_scope", "Token does not carry mcp:sql scope"),
                    ("inactive_or_non_staff", "User is not an active staff member"),
                    ("no_mfa", "User does not have a verified TOTP device"),
                    ("no_perm", "User holds no MCP profile permission"),
                    (
                        "ambiguous_profile",
                        "User is assigned to more than one MCP profile",
                    ),
                    ("no_session", "User has no live Django session"),
                    ("session_logout", "MCP tokens revoked on user logout"),
                ],
                max_length=64,
            ),
        ),
    ]
