# Generated by Django 5.2.15 on 2026-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0011_alter_mcpquerylog_options_mcpquerylog_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpauthrejectionlog',
            name='client_redirect',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mcpquerylog',
            name='client_redirect',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
