# Generated by Django 5.2.15 on 2026-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0012_mcpauthrejectionlog_client_redirect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpauthrejectionlog',
            name='client_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='mcpquerylog',
            name='application_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mcpquerylog',
            name='client_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
