# Generated by Django 5.2.17 on 2026-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0012_mcpauthrejectionlog_client_redirect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPRefreshTokenFamily',
            fields=[
                ('token_family', models.UUIDField(primary_key=True, serialize=False)),
                ('consented_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'MCP refresh-token family',
                'verbose_name_plural': 'MCP refresh-token families',
            },
        ),
        migrations.AlterField(
            model_name='mcpauthrejectionlog',
            name='reason',
            field=models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive_or_non_staff', 'User is not an active staff member'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User holds no MCP profile permission'), ('ambiguous_profile', 'User is assigned to more than one MCP profile'), ('no_session', 'User has no live Django session'), ('session_logout', 'MCP tokens revoked on user logout'), ('password_change', 'MCP tokens revoked on password change')], max_length=64),
        ),
    ]
