# Generated by Django 5.2.17 on 2026-10-06 13:31
"""`MCPRefreshTokenFamily` (opt-in refresh tokens' consent record) + the
`password_change` audit reason.

The `REVOKE SELECT ... FROM mcp_readonly_role` RunSQL is hand-added, as in
0002 / 0008 for the package's other tables: defense in depth against a
broad `GRANT SELECT ON ALL TABLES` / `ALTER DEFAULT PRIVILEGES ... TO
mcp_readonly_role` exposing the table to `run_query`. The DO/EXCEPTION
wrapper keeps it safe where the role does not exist yet.
"""

from django.db import migrations, models

REVOKE_REFRESH_FAMILY_FROM_READONLY = """
DO $$
BEGIN
    REVOKE SELECT ON mcp_sql_mcprefreshtokenfamily FROM mcp_readonly_role;
EXCEPTION
    WHEN undefined_object THEN
        NULL;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0012_mcpauthrejectionlog_client_redirect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPRefreshTokenFamily',
            fields=[
                ('token_family', models.UUIDField(primary_key=True, serialize=False)),
                ('consented_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'MCP refresh-token family',
                'verbose_name_plural': 'MCP refresh-token families',
            },
        ),
        migrations.RunSQL(
            REVOKE_REFRESH_FAMILY_FROM_READONLY,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='mcpauthrejectionlog',
            name='reason',
            field=models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive_or_non_staff', 'User is not an active staff member'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User holds no MCP profile permission'), ('ambiguous_profile', 'User is assigned to more than one MCP profile'), ('no_session', 'User has no live Django session'), ('session_logout', 'MCP tokens revoked on user logout'), ('password_change', 'MCP tokens revoked on password change')], max_length=64),
        ),
    ]
