# Generated by Django 6.0.8 on 2026-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0013_client_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpauthrejectionlog',
            name='reason',
            field=models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive', 'User account is inactive'), ('inactive_or_non_staff', 'User is not an active staff member (up to 0.1.x)'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User holds no MCP profile permission'), ('ambiguous_profile', 'User is assigned to more than one MCP profile'), ('no_session', 'User has no live Django session'), ('session_logout', 'MCP tokens revoked on user logout')], max_length=64),
        ),
    ]
