# Generated by Django 6.0.8 on 2026-10-06 12:44

# Unreleased (0.2.0b1): also carries the `gate_error` choice, folded in here
# rather than in a new migration, and keeps 0013's `password_change` choice
# (0013_refresh_token_family, merged in before this one). Choices live only in migration state, never
# in the schema, so a database that applied the earlier form is unaffected.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_sql', '0014_client_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpauthrejectionlog',
            name='reason',
            field=models.CharField(choices=[('bad_application', 'Token not issued by an mcp-sql Application'), ('bad_scope', 'Token does not carry mcp:sql scope'), ('inactive', 'User account is inactive'), ('inactive_or_non_staff', 'User is not an active staff member (up to 0.1.x)'), ('no_mfa', 'User does not have a verified TOTP device'), ('no_perm', 'User holds no MCP profile permission'), ('ambiguous_profile', 'User is assigned to more than one MCP profile'), ('no_session', 'User has no live Django session'), ('gate_error', 'A per-request gate failed; access could not be verified'), ('session_logout', 'MCP tokens revoked on user logout'), ('password_change', 'MCP tokens revoked on password change')], max_length=64),
        ),
    ]
