"""Emit the per-profile Postgres role bootstrap SQL from `MCP_SQL["PROFILES"]`.

Generalises `sql/role_setup.sql` (one hand-written role) to N roles read from
settings. Read-only: it only PRINTS SQL to stdout for a DBA to review and run
as a superuser — it never connects or applies. On stage/prod the role + GUC
defaults + membership grant are a manual DBA step regardless; this keeps that
SQL a generated function of `PROFILES` rather than a file to hand-edit per
new tier. On local/test the example app pipes this into `psql` (see its
Makefile `roles` target).

Mirrors `role_setup.sql`'s shape exactly: an idempotent `CREATE ROLE … NOLOGIN`
(swallowing `duplicate_object`), the four session GUC defaults via `ALTER ROLE`
(sourced from `session.EXPECTED_SESSION_GUCS` so they never drift from the
runtime `SET LOCAL` guards), and the membership `GRANT … TO <app_role>` block
that reads the connecting role from the psql variable `app_role` via a
`SET LOCAL` + `current_setting` dance (psql does not substitute `:'…'` inside
`DO $$ … $$`). Run as:

    python manage.py mcp_sql_role_setup --emit-sql | psql ... -v app_role=<role>
"""

from django.core.management.base import BaseCommand
from django.core.management.base import CommandError
from mcp_sql.conf import mcp_sql_settings
from mcp_sql.session import EXPECTED_SESSION_GUCS

_HEADER = (
    "-- Generated by `manage.py mcp_sql_role_setup --emit-sql` from PROFILES.\n"
    "-- One NOLOGIN role per profile + its session GUC defaults + the membership\n"
    "-- GRANT to the connecting app role. Mirrors mcp_sql/sql/role_setup.sql;\n"
    "-- review before running. Apply as a superuser, passing the connecting role\n"
    "-- via -v app_role=<role>. Idempotent: re-running must not fail.\n"
)


def _role_block(role: str) -> str:
    guc_lines = "\n".join(
        f"ALTER ROLE {role} SET {name} = '{value}';"
        for name, value in EXPECTED_SESSION_GUCS.items()
    )
    return (
        "DO $$\n"
        "BEGIN\n"
        f"    CREATE ROLE {role} NOLOGIN;\n"
        "EXCEPTION\n"
        "    WHEN duplicate_object THEN\n"
        "        NULL;\n"
        "END\n"
        "$$;\n\n"
        f"{guc_lines}\n"
    )


def _membership_block(roles: list[str]) -> str:
    grants = "\n".join(
        f"    EXECUTE format('GRANT {role} TO %I', target_role);" for role in roles
    )
    return (
        "BEGIN;\n\n"
        "SET LOCAL mcp_sql.app_role = :'app_role';\n\n"
        "DO $$\n"
        "DECLARE\n"
        "    target_role text := current_setting('mcp_sql.app_role');\n"
        "BEGIN\n"
        f"{grants}\n"
        "EXCEPTION\n"
        "    WHEN undefined_object THEN\n"
        '        RAISE NOTICE \'app role "%" does not yet exist in this cluster; '
        "membership not granted. Create the role, then re-run with "
        "-v app_role=<role>.', target_role;\n"
        "END\n"
        "$$;\n\n"
        "COMMIT;\n"
    )


class Command(BaseCommand):
    help = (
        'Print the Postgres role bootstrap SQL derived from MCP_SQL["PROFILES"] '
        "(one NOLOGIN role per distinct profile role + GUC defaults + membership "
        "GRANT). Read-only: prints to stdout for a DBA to review and run; never "
        "connects or applies. Pass the connecting role to psql via "
        "-v app_role=<role>."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--emit-sql",
            action="store_true",
            help=(
                "Print the bootstrap SQL to stdout. Required — the command has "
                "no apply mode; a DBA runs the emitted SQL."
            ),
        )

    def handle(self, *args, **options):
        if not options["emit_sql"]:
            msg = (
                "Pass --emit-sql to print the role bootstrap SQL "
                "(this command never applies it itself)."
            )
            raise CommandError(msg)

        # Distinct roles, in first-seen profile order. Validation enforces
        # ROLE uniqueness across profiles, so the dedup below is
        # belt-and-braces (relaxing the validator to allow role sharing would
        # need a grants-reconcile redesign first — two profiles reconciling
        # one role's grants is last-writer-wins).
        roles: list[str] = []
        for profile in mcp_sql_settings.profiles().values():
            if profile.role not in roles:
                roles.append(profile.role)

        blocks = [
            _HEADER,
            *[_role_block(role) for role in roles],
            _membership_block(roles),
        ]
        self.stdout.write("\n".join(blocks))
